version: "3.9"

services:
  backend:
    build:
      context: ./backend  # ✅ Corrected build path
      dockerfile: Dockerfile  # ✅ Explicitly specify Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db/continuous_auth

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pravin0606
      MYSQL_DATABASE: continuous_auth
    ports:
      - "3307:3306"  # ✅ Changed to avoid conflict with existing MySQL process

  frontend:
    build:
      context: ./frontend  # ✅ Corrected indentation
      dockerfile: Dockerfile  # ✅ Explicitly specify Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # ✅ Fixed indentation
